# Production Profile - Full observability with metrics, tracing, and logging
spring:
  application:
    name: product-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres-service:5432/productdb}
    username: ${DB_USERNAME:product_user}
    password: ${DB_PASSWORD:product_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC



# Structured JSON logging for production
logging:
  level:
    com.sparkage: INFO
    org.hibernate.SQL: WARN
