apiVersion: v2
name: observability-stack
description: A comprehensive observability stack including Prometheus, Grafana, ELK Stack, and Jaeger for cloud-native microservices
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - observability
  - monitoring
  - logging
  - tracing
  - prometheus
  - grafana
  - elasticsearch
  - logstash
  - kibana
  - jaeger
home: https://github.com/sparkage/mis-cloud-native-research
maintainers:
  - name: Sparkage Team
    email: team@sparkage.com
dependencies: []

