# Production Environment Values - High Availability, Enhanced Security, and Comprehensive Observability
global:
  environment: "production"
  imageRegistry: "ghcr.io"
  imagePullPolicy: IfNotPresent
  gcp:
    projectId: "mis-cloud-native-research"
    region: "us-central1"

# Production API Gateway configuration with enhanced security and performance
services:
  api-gateway:
    replicaCount: 3  # High availability
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
    security:
      apiKeys: "WILL_BE_SET_FROM_SECRET_MANAGER"
      headerName: "X-API-Key"
    rateLimit:
      replenishRate: 100
      burstCapacity: 200
    env:
      - name: SPRING_PROFILES_ACTIVE
        value: "production"
      - name: LOGGING_LEVEL_COM_SPARKAGE
        value: "INFO"
      - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY
        value: "WARN"
      - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
        value: "when-authorized"
    # Production HPA configuration
    hpa:
      enabled: true
      minReplicas: 2
      maxReplicas: 10
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80

  # Enable all services for production
  identity:
    enabled: true
    replicaCount: 2
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    hpa:
      enabled: true
      minReplicas: 2
      maxReplicas: 5

  product:
    enabled: true
    replicaCount: 2
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    hpa:
      enabled: true
      minReplicas: 2
      maxReplicas: 5

  cart:
    enabled: true
    replicaCount: 2
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "400m"
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 3

  order:
    enabled: true
    replicaCount: 2
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    hpa:
      enabled: true
      minReplicas: 2
      maxReplicas: 5

  payment:
    enabled: true
    replicaCount: 2
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "400m"
    hpa:
      enabled: true
      minReplicas: 2
      maxReplicas: 4


# Production ingress with SSL
ingress:
  enabled: true
  className: "gce"
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "mis-cloud-native-ip"
    networking.gke.io/managed-certificates: "mis-cloud-native-ssl-cert"
    kubernetes.io/ingress.allow-http: "false"
  hosts:
    - host: api.mis-cloud-native.com
      paths:
        - path: /
          pathType: Prefix
          service:
            name: api-gateway
            port: 8080
  tls:
    - secretName: mis-cloud-native-tls
      hosts:
        - api.mis-cloud-native.com
