# Production Environment Values - Minimal but Resilient Resources
global:
  environment: "production"
  imagePullPolicy: IfNotPresent
  imageRegistry: "ghcr.io"
  gcp:
    projectId: ""  # Will be set via GitHub Actions
    region: "us-central1"
    cluster:
      name: ""  # Will be set via GitHub Actions
  ingress:
    enabled: true
    className: "gce"
    hosts:
      - host: "api.your-domain.com"
        paths:
          - path: "/"
            pathType: "Prefix"
            service: "api-gateway"
    tls: []  # Add TLS configuration when ready

# Minimal but production-ready resources
services:
  api-gateway:
    replicaCount: 2  # At least 2 for HA
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "200m"
    security:
      apiKeys: ""  # Will be set via secrets in GitHub Actions
      headerName: "X-API-Key"
    rateLimit:
      replenishRate: 10  # More restrictive for production
      burstCapacity: 20

  identity:
    replicaCount: 2
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "100m"

  product:
    replicaCount: 2
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "100m"

  cart:
    replicaCount: 2
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "100m"

  order:
    replicaCount: 2
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "100m"

  payment:
    replicaCount: 2
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "100m"

# Basic observability for production
observability:
  enabled: true
  prometheus:
    enabled: true
    namespace: observability
  grafana:
    enabled: false  # Disabled for minimal setup
  elk:
    enabled: false  # Disabled for minimal setup
  jaeger:
    enabled: false  # Disabled for minimal setup
