# Development Environment Values - Minimal Resources
global:
  environment: "development"
  imageRegistry: "ghcr.io"
  imagePullPolicy: Always
  gcp:
    projectId: "mis-cloud-native-research"
    region: "us-central1"

# Override API Gateway configuration for development
services:
  api-gateway:
    replicaCount: 1
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "200m"
    security:
      apiKeys: "dev-api-key-12345"
      headerName: "X-API-Key"
    rateLimit:
      replenishRate: 5
      burstCapacity: 10
    env:
      - name: SPRING_PROFILES_ACTIVE
        value: "development"
      - name: LOGGING_LEVEL_COM_SPARKAGE
        value: "DEBUG"
      - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY
        value: "DEBUG"
      # Downward API for namespace (used in OTEL resource attributes)
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      # OpenTelemetry tracing to in-cluster Alloy receiver (OTLP/HTTP)
      - name: OTEL_SERVICE_NAME
        value: "api-gateway"
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: "service.name=api-gateway,service.namespace=$(POD_NAMESPACE),deployment.environment=development"
      - name: OTEL_TRACES_EXPORTER
        value: "otlp"
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "http/protobuf"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://grafana-k8s-monitoring-alloy-receiver.grafana.svc.cluster.local:4318"
      - name: OTEL_PROPAGATORS
        value: "tracecontext,baggage"

  # Enable only essential services for development
  identity:
    enabled: true
    replicaCount: 1
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "100m"

  product:
    enabled: true
    replicaCount: 1
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "100m"

  cart:
    enabled: false  # Disable for development

  order:
    enabled: false  # Disable for development

  payment:
    enabled: false  # Disable for development

