version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: identity-postgres
    environment:
      POSTGRES_DB: identitydb
      POSTGRES_USER: identity
      POSTGRES_PASSWORD: identity
    ports:
      - "5432:5432"
    volumes:
      - pgdata_identity:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdata_identity:
