version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: product-postgres
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: product
      POSTGRES_PASSWORD: product
    ports:
      - "5433:5432"
    volumes:
      - pgdata_product:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdata_product:
