{{- if (index .Values.services "api-gateway").enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-security
type: Opaque
data:
  apiKeys: {{ index .Values.services "api-gateway" "security" "apiKeys" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-api-gateway
type: Opaque
data:
  {{- with index .Values.services "api-gateway" "db" }}
  SPRING_DATASOURCE_URL: {{ .url | b64enc | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .username | b64enc | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .password | b64enc | quote }}
  {{- end }}
{{- end }}
