{{- $global := .Values.global -}}
{{- range $key, $svc := .Values.services }}
{{- if $svc.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" $.Release.Name $key | trunc 63 | trimSuffix "-" }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $key }}
spec:
  replicas: {{ $svc.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: {{ $key }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/component: {{ $key }}
    spec:
      containers:
        - name: {{ $key }}
          image: {{ $svc.image }}
          imagePullPolicy: {{ $global.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ $svc.containerPort | default 8080 }}
              protocol: TCP
          {{- if $svc.usesDb }}
          envFrom:
            - secretRef:
                name: {{ printf "db-%s" $key }}
          {{- end }}
          env:
            {{- range $svc.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: {{ $svc.readinessProbe.path | default "/actuator/health" }}
              port: http
            initialDelaySeconds: {{ $svc.readinessProbe.initialDelaySeconds | default 10 }}
            periodSeconds: {{ $svc.readinessProbe.periodSeconds | default 10 }}
          livenessProbe:
            httpGet:
              path: {{ $svc.livenessProbe.path | default "/actuator/health" }}
              port: http
            initialDelaySeconds: {{ $svc.livenessProbe.initialDelaySeconds | default 20 }}
            periodSeconds: {{ $svc.livenessProbe.periodSeconds | default 10 }}
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            {{- toYaml ($svc.resources | default dict) | nindent 12 }}
---
{{- end }}
{{- end }}
