# Placeholder for optional Grafana Cloud Secret template.
# Provide your Secret manifest separately or create it manually:
# kubectl create secret generic grafana-cloud-credentials \
#   --from-literal=api_key=REDACTED \
#   --from-literal=stack_id=YOUR_STACK_ID
