{{- range $key, $svc := .Values.services }}
{{- if and $svc.enabled $svc.autoscaling $svc.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ printf "%s-%s" $.Release.Name $key | trunc 63 | trimSuffix "-" }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $key }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ printf "%s-%s" $.Release.Name $key | trunc 63 | trimSuffix "-" }}
  minReplicas: {{ $svc.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ $svc.autoscaling.maxReplicas | default 3 }}
  metrics:
    {{- $cpu := $svc.autoscaling.targetCPUUtilizationPercentage }}
    {{- $mem := $svc.autoscaling.targetMemoryUtilizationPercentage }}
    {{- if or $cpu $mem }}
    {{- if $cpu }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $cpu }}
    {{- end }}
    {{- if $mem }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $mem }}
    {{- end }}
    {{- else }}
    # Default to CPU metric if none specified
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    {{- end }}
---
{{- end }}
{{- end }}
