apiVersion: v1
kind: ConfigMap
metadata:
  name: microservice-observability-config
  namespace: default
  labels:
    app.kubernetes.io/name: microservice-observability
    app.kubernetes.io/component: configuration
data:
  # Observability endpoints - these will be injected into microservices
  LOGSTASH_HOST: "logstash-service.observability.svc.cluster.local"
  LOGSTASH_PORT: "5000"
  JAEGER_AGENT_HOST: "jaeger-agent-service.observability.svc.cluster.local"
  JAEGER_AGENT_PORT: "6831"
  JAEGER_COLLECTOR_HOST: "jaeger-collector-service.observability.svc.cluster.local"
  JAEGER_COLLECTOR_PORT: "14268"
  PROMETHEUS_HOST: "prometheus-service.observability.svc.cluster.local"
  PROMETHEUS_PORT: "9090"

  # Spring Boot Actuator configuration
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
  MANAGEMENT_ENDPOINT_METRICS_ENABLED: "true"
  MANAGEMENT_ENDPOINT_HEALTH_ENABLED: "true"
  MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"

  # Logging configuration for structured JSON logs
  LOGGING_LEVEL_COM_SPARKAGE: "DEBUG"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY: "DEBUG"

  # OpenTracing Jaeger configuration
  OPENTRACING_JAEGER_SAMPLER_TYPE: "const"
  OPENTRACING_JAEGER_SAMPLER_PARAM: "1"
  OPENTRACING_JAEGER_LOG_SPANS: "false"
  OPENTRACING_JAEGER_ENABLE_B3_PROPAGATION: "true"

  # Spring profiles for observability
  SPRING_PROFILES_ACTIVE: "kubernetes,observability"

