{{- range $key, $svc := .Values.services }}
{{- if $svc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" $.Release.Name $key | trunc 63 | trimSuffix "-" }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $key }}
spec:
  type: {{ $svc.service.type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $key }}
  ports:
    - name: http
      port: {{ $svc.service.port | default 80 }}
      targetPort: {{ $svc.containerPort | default 8080 }}
      protocol: TCP
---
{{- end }}
{{- end }}
