apiVersion: v1
kind: Namespace
metadata:
  name: observability-prod
  labels:
    name: observability-prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-light
  namespace: observability-prod
  labels:
    app: elasticsearch
    component: search-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
        component: search-engine
    spec:
      initContainers:
      - name: set-vm-max-map-count
        image: busybox:1.35
        command: ['sh', '-c', 'echo "vm.max_map_count=262144" > /proc/sys/vm/max_map_count || true']
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        env:
        - name: discovery.type
          value: "single-node"
        - name: ES_JAVA_OPTS
          value: "-Xms256m -Xmx256m"
        - name: xpack.security.enabled
          value: "false"
        - name: xpack.monitoring.enabled
          value: "false"
        - name: cluster.routing.allocation.disk.threshold_enabled
          value: "false"
        - name: bootstrap.memory_lock
          value: "false"
        - name: cluster.name
          value: "elasticsearch-cluster"
        - name: node.name
          value: "elasticsearch-node-1"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: elasticsearch-storage
          mountPath: /usr/share/elasticsearch/data
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
          initialDelaySeconds: 60
          periodSeconds: 30
      volumes:
      - name: elasticsearch-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: observability-prod
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - port: 9200
    targetPort: 9200
    name: http
  - port: 9300
    targetPort: 9300
    name: transport
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: observability-prod
data:
  logstash.conf: |
    input {
      tcp {
        port => 5000
        codec => json_lines
      }
      beats {
        port => 5044
      }
    }
    
    filter {
      if [service] {
        mutate {
          add_field => { "[@metadata][service]" => "%{service}" }
        }
      }
      
      # Parse timestamp
      date {
        match => [ "timestamp", "ISO8601" ]
      }
      
      # Add additional fields
      mutate {
        add_field => { "environment" => "production" }
        add_field => { "cluster" => "kubernetes" }
      }
      
      # Parse log levels
      if [level] {
        mutate {
          uppercase => [ "level" ]
        }
      }
    }
    
    output {
      elasticsearch {
        hosts => ["elasticsearch-service:9200"]
        index => "microservices-logs-%{+YYYY.MM.dd}"
        template_name => "microservices"
        template_pattern => "microservices-*"
        template => {
          "index_patterns" => ["microservices-*"]
          "settings" => {
            "number_of_shards" => 1
            "number_of_replicas" => 0
            "index.refresh_interval" => "5s"
          }
          "mappings" => {
            "properties" => {
              "@timestamp" => { "type" => "date" }
              "service" => { "type" => "keyword" }
              "level" => { "type" => "keyword" }
              "message" => { "type" => "text" }
              "traceId" => { "type" => "keyword" }
              "spanId" => { "type" => "keyword" }
              "environment" => { "type" => "keyword" }
              "host" => { "type" => "keyword" }
              "logger" => { "type" => "keyword" }
            }
          }
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: observability-prod
  labels:
    app: logstash
    component: log-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
        component: log-processor
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:8.8.0
        ports:
        - containerPort: 5000
          name: tcp
        - containerPort: 5044
          name: beats
        - containerPort: 9600
          name: http
        volumeMounts:
        - name: logstash-config
          mountPath: /usr/share/logstash/pipeline
        env:
        - name: LS_JAVA_OPTS
          value: "-Xms256m -Xmx256m"
        - name: XPACK_MONITORING_ENABLED
          value: "false"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /
            port: 9600
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 9600
          initialDelaySeconds: 60
          periodSeconds: 30
      volumes:
      - name: logstash-config
        configMap:
          name: logstash-config
---
apiVersion: v1
kind: Service
metadata:
  name: logstash-service
  namespace: observability-prod
  labels:
    app: logstash
spec:
  selector:
    app: logstash
  ports:
  - port: 5000
    targetPort: 5000
    name: tcp
  - port: 5044
    targetPort: 5044
    name: beats
  - port: 9600
    targetPort: 9600
    name: http
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: observability-prod
  labels:
    app: kibana
    component: visualization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
        component: visualization
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.8.0
        ports:
        - containerPort: 5601
          name: http
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch-service:9200"
        - name: XPACK_SECURITY_ENABLED
          value: "false"
        - name: SERVER_NAME
          value: "kibana"
        - name: SERVER_HOST
          value: "0.0.0.0"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /api/status
            port: 5601
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/status
            port: 5601
          initialDelaySeconds: 120
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  namespace: observability-prod
  labels:
    app: kibana
spec:
  selector:
    app: kibana
  ports:
  - port: 5601
    targetPort: 5601
    name: http
  type: ClusterIP
---
# Ingress for external access
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elk-ingress
  namespace: observability-prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: kibana.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kibana-service
            port:
              number: 5601
  - host: elasticsearch.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: elasticsearch-service
            port:
              number: 9200
