# Default configuration - development profile (no observability)
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  profiles:
    active: development
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
        - RemoveResponseHeader=Server
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
            allowedHeaders: "*"
            maxAge: 3600
      routes:
        - id: identity
          uri: ${IDENTITY_URI:http://localhost:9000}
          predicates:
            - Path=/api/identity/**
          filters:
            - StripPrefix=2
        - id: product
          uri: ${PRODUCT_URI:http://localhost:9001}
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=2
        - id: cart
          uri: ${CART_URI:http://localhost:9002}
          predicates:
            - Path=/api/cart/**
          filters:
            - StripPrefix=2
        - id: order
          uri: ${ORDER_URI:http://localhost:9003}
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=2
        - id: payment
          uri: ${PAYMENT_URI:http://localhost:9004}
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=2

server:
  port: ${SERVER_PORT:8080}

# Basic logging for development
logging:
  level:
    com.sparkage: INFO
    org.springframework.cloud.gateway: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Basic management endpoints (no observability)
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      enabled: true
      show-details: when-authorized
