spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://product-service:8081
          predicates:
            - Path=/api/products/**
        - id: order-service
          uri: http://order-service:8082
          predicates:
            - Path=/api/orders/**
        - id: cart-service
          uri: http://cart-service:8083
          predicates:
            - Path=/api/cart/**
        - id: payment-service
          uri: http://payment-service:8084
          predicates:
            - Path=/api/payments/**
        - id: identity-service
          uri: http://identity-service:8085
          predicates:
            - Path=/api/auth/**
  security:
    user:
      name: admin
      password: admin123

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    reactor.netty: DEBUG
    com.sparkage: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  endpoint:
    health:
      show-details: always
