spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
        - RemoveResponseHeader=Server
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: ${RATELIMIT_REPLENISH_RATE:10}
            redis-rate-limiter.burstCapacity: ${RATELIMIT_BURST_CAPACITY:20}
            key-resolver: "#{@ipKeyResolver}"
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
            allowedHeaders: "*"
            maxAge: 3600
      routes:
        - id: identity
          uri: ${IDENTITY_URI:http://identity-service:8085}
          predicates:
            - Path=/api/identity/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: identity-cb
                fallbackUri: forward:/fallback/identity
        - id: product
          uri: ${PRODUCT_URI:http://product-service:8081}
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: product-cb
                fallbackUri: forward:/fallback/product
        - id: cart
          uri: ${CART_URI:http://cart-service:8082}
          predicates:
            - Path=/api/cart/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: cart-cb
                fallbackUri: forward:/fallback/cart
        - id: order
          uri: ${ORDER_URI:http://order-service:8083}
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: order-cb
                fallbackUri: forward:/fallback/order
        - id: payment
          uri: ${PAYMENT_URI:http://payment-service:8084}
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: payment-cb
                fallbackUri: forward:/fallback/payment

server:
  port: ${SERVER_PORT:8080}

# Management endpoints for development
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  endpoint:
    health:
      enabled: true
      show-details: always
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
    tags:
      application: ${spring.application.name}
      environment: development
  prometheus:
    metrics:
      export:
        enabled: true
  simple:
    metrics:
      export:
        enabled: false
  tracing:
    sampling:
      probability: ${OTEL_SAMPLING_PROBABILITY:1.0}

# OpenTelemetry to Grafana Cloud or in-cluster Alloy (override via env)
otel:
  traces:
    exporter: ${OTEL_TRACES_EXPORTER:otlp}
  exporter:
    otlp:
      protocol: ${OTEL_EXPORTER_OTLP_PROTOCOL:http/protobuf}
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://grafana-k8s-monitoring-alloy-receiver.grafana.svc.cluster.local:4318}
      headers: ${OTEL_EXPORTER_OTLP_HEADERS:}
  propagators: ${OTEL_PROPAGATORS:tracecontext,baggage}
