management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      service: api-gateway
    web:
      server:
        request:
          autotime:
            enabled: true

# Jaeger Tracing Configuration
opentracing:
  jaeger:
    service-name: ${spring.application.name}
    sampler:
      type: const
      param: 1
    reporter:
      log-spans: true
      max-queue-size: 100
      flush-interval: 1000
    udp-sender:
      host: jaeger-agent
      port: 6831

# Logging Configuration
logging:
  level:
    com.sparkage: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
  file:
    name: /var/log/api-gateway.log

spring:
  application:
    name: api-gateway
