spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://product-service.staging.svc.cluster.local:8081
          predicates:
            - Path=/api/products/**
        - id: order-service
          uri: http://order-service.staging.svc.cluster.local:8082
          predicates:
            - Path=/api/orders/**
        - id: cart-service
          uri: http://cart-service.staging.svc.cluster.local:8083
          predicates:
            - Path=/api/cart/**
        - id: payment-service
          uri: http://payment-service.staging.svc.cluster.local:8084
          predicates:
            - Path=/api/payments/**
        - id: identity-service
          uri: http://identity-service.staging.svc.cluster.local:8085
          predicates:
            - Path=/api/auth/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://identity-service.staging.svc.cluster.local:8085}

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.web: WARN
    com.sparkage: INFO
  file:
    name: logs/api-gateway.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

ENV: staging
