{{- if .Values.logstash.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: {{ include "observability-stack.namespace" . }}
  labels:
    {{- include "observability-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "observability-stack.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: logstash
  template:
    metadata:
      labels:
        {{- include "observability-stack.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: logstash
    spec:
      containers:
      - name: logstash
        image: "{{ .Values.logstash.image.repository }}:{{ .Values.logstash.image.tag }}"
        imagePullPolicy: {{ .Values.logstash.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.logstash.service.tcpPort }}
          name: tcp
        - containerPort: {{ .Values.logstash.service.httpPort }}
          name: http
        - containerPort: 5044
          name: beats
        volumeMounts:
        - name: logstash-config
          mountPath: /usr/share/logstash/pipeline
        - name: logstash-settings
          mountPath: /usr/share/logstash/config
        env:
        - name: LS_JAVA_OPTS
          value: "-Xms{{ .Values.logstash.config.heapSize }} -Xmx{{ .Values.logstash.config.heapSize }}"
        - name: XPACK_MONITORING_ENABLED
          value: "false"
        resources:
          {{- toYaml .Values.logstash.resources | nindent 10 }}
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: logstash-config
        configMap:
          name: logstash-config
          items:
          - key: logstash.conf
            path: logstash.conf
      - name: logstash-settings
        configMap:
          name: logstash-config
          items:
          - key: logstash.yml
            path: logstash.yml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

