name: "01 - Build and Test"

on:
  push:
    branches: [ main ]
    paths:
      - 'services/**'
      - '.github/workflows/01-build-test.yml'
      - 'scripts/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  JAVA_VERSION: '17'
  MAVEN_OPTS: '-Dmaven.repo.local=.m2/repository'
  WORKSPACE_DIR: ${{ github.workspace }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: [api-gateway, identity, product, cart, order, payment]

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: 'maven'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: .m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Build Service
      working-directory: services/${{ matrix.service }}
      run: mvn -B clean package -DskipTests

    - name: Run Unit Tests
      working-directory: services/${{ matrix.service }}
      run: mvn -B test

    - name: Run Integration Tests
      working-directory: ${{ github.workspace }}
      run: |
        chmod +x scripts/run_tests.sh
        ./scripts/run_tests.sh ${{ matrix.service }}

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.service }}
        path: services/${{ matrix.service }}/target/surefire-reports

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.service }}-artifact
        path: |
          services/${{ matrix.service }}/target/*.jar
          !services/${{ matrix.service }}/target/*-sources.jar
          !services/${{ matrix.service }}/target/*-javadoc.jar
        retention-days: 1
        if-no-files-found: error
        compression-level: 9
