name: "04 - Infrastructure"

on:
  workflow_run:
    workflows: ["03 - Container Build & Security"]
    types:
      - completed
  workflow_dispatch:

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GKE_CLUSTER: mis-cloud-native-gke
  GKE_REGION: us-central1

permissions:
  contents: read
  id-token: write

jobs:
  setup-infrastructure:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        project_id: '${{ secrets.GCP_PROJECT }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.5.0"

    - name: Create Infrastructure
      run: |
        chmod +x ./scripts/create_infra.sh
        ./scripts/create_infra.sh

    - name: Validate Infrastructure
      run: |
        chmod +x ./scripts/validate_infra.sh
        ./scripts/validate_infra.sh

    - name: Setup Database
      run: |
        chmod +x ./scripts/create_db.sh
        ./scripts/create_db.sh

    - name: Create Secrets
      run: |
        chmod +x ./scripts/create_secrets.sh
        ./scripts/create_secrets.sh
