name: Terraform GKE and Dependencies

on:
  push:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

env:
  TF_WORKING_DIR: terraform

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          TF_VAR_gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
          TF_VAR_gcp_region: ${{ vars.GCP_REGION || 'us-central1' }}
          TF_VAR_gcp_zone: ${{ vars.GCP_ZONE || 'us-central1-a' }}
        run: terraform init -input=false

      - name: Terraform Format
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name != 'workflow_dispatch'
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          TF_VAR_gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
          TF_VAR_gcp_region: ${{ vars.GCP_REGION || 'us-central1' }}
          TF_VAR_gcp_zone: ${{ vars.GCP_ZONE || 'us-central1-a' }}
        run: terraform plan -input=false

      - name: Terraform Apply (manual)
        if: github.event_name == 'workflow_dispatch'
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          TF_VAR_gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
          TF_VAR_gcp_region: ${{ vars.GCP_REGION || 'us-central1' }}
          TF_VAR_gcp_zone: ${{ vars.GCP_ZONE || 'us-central1-a' }}
        run: terraform apply -auto-approve -input=false
